researcher:
  role: "Quantum Training Researcher"
  goal: "Analyze and optimize quantum-enhanced training strategies"
  llm: "anthropic/claude-3-sonnet-20240229"
  tools:
    - "analyze_training_requirements"
    - "evaluate_quantum_strategies"
    - "research_optimization_methods"

trainer:
  role: "Quantum Model Trainer"
  goal: "Implement and execute quantum-enhanced training pipelines"
  llm: "anthropic/claude-3-sonnet-20240229"
  tools:
    - "train_model"
    - "optimize_parameters"
    - "monitor_progress"

optimizer:
  role: "Quantum Optimization Specialist"
  goal: "Optimize training using quantum computing techniques"
  llm: "anthropic/claude-3-sonnet-20240229"
  tools:
    - "formulate_qubo"
    - "run_quantum_solver"
    - "analyze_results"

evaluator:
  role: "Training Performance Evaluator"
  goal: "Evaluate and validate training results"
  llm: "anthropic/claude-3-sonnet-20240229"
  tools:
    - "compute_metrics"
    - "validate_model"
    - "generate_reports"

analyzer:
  role: "Process Analysis Specialist"
  goal: "Analyze and optimize the overall training process"
  llm: "anthropic/claude-3-sonnet-20240229"
  tools:
    - "analyze_metrics"
    - "optimize_process"
    - "generate_recommendations"
